config/routes.rb
Shoutsus::Application.routes.draw do

  resources :shouts do
    collection do
      get :fetch
    end
  end

  root :to => "shouts#index"

  devise_for :users
end

app/models/shout.rb
class Shout < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :user, :message

  default_scope order('id DESC')
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :login
  validates_uniqueness_of :login

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :login
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
end

app/controllers/shouts_controller.rb
class ShoutsController < InheritedResources::Base
  before_filter :authenticate_user!
  before_filter :assign_user, :only => [:create]

  respond_to  :html, :js

  def index
    @shout = Shout.new
    index!
  end

  def fetch
    collection
  end

  protected

  def collection
    @shouts ||= end_of_association_chain.paginate(:page => params[:page])
  end

  private

  def assign_user
    params[:shout][:user] = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def message(name)
    "<div class='#{name}'>#{eval(name.to_s)}</div>" if eval(name.to_s)
  end
end

app/helpers/shouts_helper.rb
module ShoutsHelper
end

app/views/layouts/application.html.haml
!!! XML
!!!
%html
  %head
    %title SU's shout
    = stylesheet_link_tag 'stylesheet'
    /[if lt IE 8]
      = stylesheet_link_tag 'ie', :media => 'screen'
    = csrf_meta_tag
  %body
    #container
      #header
        %h1 Shout SUS's
        - if user_signed_in?
          .logout=link_to 'logout', destroy_user_session_path
      #content
        #flash= %w(notice alert).map { |key| message(key) }.join.html_safe
        = yield
      #footer

    %script{ :type => "text/javascript", :src => "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" }
    %script{ :type => "text/javascript", :src => "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js" }
    = javascript_include_tag :all

app/views/shared/_shout.haml
.shout{ :id => "shout_#{shout.id}" }
  .avatar= gravatar_for(shout.user).html_safe
  .body= auto_link(shout.message, :html => { :target => "_blank" }) { |text| truncate(text, :length => 15) }
  .user= shout.user.login
  .date= "#{time_ago_in_words(shout.created_at)} #{I18n.t(:ago)}"
  - if shout.user == current_user
    = link_to t(:delete), shout, :remote => true, :method => :delete

app/views/shouts/create.js.erb
afterShoutCreated("<%= escape_javascript(render("shared/shout", :shout => @shout)) %>", "<%= @shout.id %>");

app/views/shouts/destroy.js.erb
removeShout(<%= @shout.id %>);

app/views/shouts/fetch.js.erb
updateShoutsFrom("<%= escape_javascript(render(:partial => "shared/shout", :collection => @shouts)) %>");

app/views/shouts/index.html.haml
= semantic_form_for @shout, :remote => true do |form|
  = form.inputs do
    = form.input :message, :label => false
  = form.buttons do
    = form.commit_button :label => "post!!"

.shouts= render :partial => 'shared/shout', :collection =>  @shouts
= link_to t(:update), fetch_shouts_path, :remote => true, :id => "update_shouts"